- name: Playbook
  hosts: all
  gather_facts: yes
  vars:
    SW:
      - httpd
      - vsftpd
      - ftp
    SRV:
      - httpd
      - vsftpd
    PORTS:
      - http
      - https
  vars_files:
    - secret.yml
  tasks:
    - name: Shell Script 
      shell: echo "Automated Script Started!"

    - name: Add New user
      user:
        name: webadmin
        state: present
        groups: wheel
        password: "{{ PASS | password_hash('sha512') }}"

    - name: checK os
      fail:
        msg: "NOT A REDHAT SW"
      when: ansible_facts.os_family != "RedHat"

    - name: incluude more tasks
      include_tasks: sw_en_tasks.yml

  handlers:
    - name: hello
      file:
        path: /tmp/hello
        state: touch

    - name: restart srv
      service:
        name: httpd
        state: restarted      

    - name: Copyfiles
      block:
      - name: touch
        file:
          path: /var/www/html/index.html
          state: touch

      - name: sent contaent
        copy:
          content: 'MY HAPPY CODE '
          dest: /var/www/html/index.html


