---
- name: Check if disk is already formatted
  command: blkid {{ device_name }}
  register: disk_check
  failed_when: false
  changed_when: false

- name: Format second disk if not formatted
  filesystem:
    fstype: xfs
    dev: "{{ device_name }}"
  when: disk_check.rc != 0

- name: Create mount directory
  file:
    path: "{{ ftp_mount_point }}"
    state: directory
    mode: '0755'

- name: Add mount entry to /etc/fstab
  mount:
    path: "{{ ftp_mount_point }}"
    src: "{{ device_name }}"
    fstype: xfs
    opts: defaults,noatime
    state: mounted

- name: Set ownership and permissions
  file:
    path: "{{ ftp_mount_point }}"
    state: directory
    owner: "{{ ftp_admin_user }}"
    group: ftpadmin
    mode: '0750'
